{% set name = "tsfresh" %}
{% set version = "0.11.2" %}
{% set sha256 = "10e73f5188abc5931b39e9ff9f25841e45db9b3825b97a26617b6b46937abb0c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - setuptools
    - requests >=2.9.1
    - numpy >=1.10.4
    - pandas >=0.20.3
    - scipy >=0.17.0
    - statsmodels >=0.6.1
    - patsy >=0.4.1
    - scikit-learn >=0.17.1
    - future >=0.16.0
    - six >=1.10.0
    - tqdm >=4.10.0

test:
  imports:
    - tsfresh

about:
  home: http://github.com/blue-yonder/tsfresh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Automatic extraction of relevant features from time series'

  doc_url: http://tsfresh.readthedocs.io/
  dev_url: https://github.com/blue-yonder/tsfresh

extra:
  recipe-maintainers:
    - MaxBenChrist
    - nils-braun
    - xhochy
