{% set name = "tsfresh" %}
{% set version = "0.18.0" %}
{% set sha256 = "ebfc1505bc0c0148909a5009190ff49f8ffe4c8c661f7cafa9da6a6ae1a9abf4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - run_tsfresh = tsfresh.scripts.run_tsfresh:main

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools_scm
    - setuptools
    - sphinx
  run:
    - python >=3.5
    - requests >=2.9.1
    - numpy >=1.15.1
    - pandas >=0.25.0
    - scipy >=1.2.0
    - statsmodels >=0.9.0
    - patsy >=0.4.1
    - scikit-learn >=0.22.0
    - tqdm >=4.10.0
    - dask >=2.9.0
    - distributed >=2.11.0
    - matrixprofile >=1.1.10,<2.0.0
    - stumpy >=1.7.2

test:
  # 2021/10/06: pip check causes an error "matrixprofile 1.1.10 has requirement protobuf==3.11.2, but you have protobuf 3.17.2."
  # but the upstream https://github.com/matrix-profile-foundation/matrixprofile/blob/v1.1.10/requirements.txt
  # uses protobuf>=3.11.2,<4.0.0, so pip check was disable.
  # Enable it when matrixprofile will be >= 1.1.11.
  #requires:
  #  - pip
  #commands:
  #  - pip check
  imports:
    - tsfresh

about:
  home: http://github.com/blue-yonder/tsfresh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Automatic extraction of relevant features from time series

  doc_url: http://tsfresh.readthedocs.io/
  dev_url: https://github.com/blue-yonder/tsfresh

extra:
  recipe-maintainers:
    - MaxBenChrist
    - nils-braun
    - xhochy
