{% set name = "tsfresh" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9942c2f78523ea12d0403b443293e45d4f1e78f750e5264fabddd2575cd75c43

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  entry_points:
    - run_tsfresh = tsfresh.scripts.run_tsfresh:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - pyscaffold >=3.3a0,<4
  run:
    - python
    - requests >=2.9.1
    - numpy >=1.15.1
    - pandas >=0.25.0
    - scipy >=1.2.0  # [py<310]
    - scipy >=1.14.0  # [py>=310]
    - statsmodels >=0.13.0
    - patsy >=0.4.1
    - pywavelets
    - cloudpickle
    - scikit-learn >=0.22.0
    - tqdm >=4.10.0
    - stumpy >=1.7.2
    - distributed >=2.11.0
    - dask >=2.9.0


{% set tests_to_skip = "test_fourier_entropy" %}
{% set tests_to_skip = tests_to_skip + " or test_spkt_welch_density" %}
{% set tests_to_skip = tests_to_skip + " or test_dict_tsframe" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_long_tsframe" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_long_tsframe_no_value_column" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_simple_data_sample_four_timeseries" %}  # [win]
{% set tests_to_skip = tests_to_skip + " or test_make_forecasting_frame_range" %}  # [win]

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - mock
    - nbformat
  imports:
    - tsfresh
  commands:
    - pip check
    - pytest tests -v -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/blue-yonder/tsfresh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Automatic extraction of relevant features from time series
  description: |
    The package provides systematic time-series feature extraction by combining established algorithms 
    from statistics, time-series analysis, signal processing, and nonlinear dynamics with a robust 
    feature selection algorithm. In this context, the term time-series is interpreted in the broadest 
    possible sense, such that any types of sampled data or even event sequences can be characterized.
  doc_url: https://tsfresh.readthedocs.io/
  dev_url: https://github.com/blue-yonder/tsfresh

extra:
  recipe-maintainers:
    - MaxBenChrist
    - nils-braun
    - xhochy
