{% set name = "tsfresh" %}
{% set version = "0.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 304316ebc20b7a33df39b9decdf1ae74c0877b8a36f1187ad2faf4e639d3f8bb

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  entry_points:
    - run_tsfresh = tsfresh.scripts.run_tsfresh:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - pyscaffold >=3.3a0,<4
  run:
    - python
    - requests >=2.9.1
    - numpy >=1.15.1
    - pandas >=0.25.0
    - scipy >=1.2.0  # [py<310]
    - scipy >=1.14.0  # [py>=310]
    - statsmodels >=0.13.0
    - patsy >=0.4.1
    - pywavelets
    - cloudpickle
    - scikit-learn >=0.22.0
    - tqdm >=4.10.0
    - stumpy >=1.7.2
    - pywavelets
  run_constrained:
    - dataframe >=2.9.0
    - distributed >=2.11.0
    - matrixprofile >=1.1.10,<2.0.0

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest >=4.4.0
    - pytest-xdist>=1.26.1
    - pytest-benchmark>=3.0.0
    - mock>=2.0.0
    - matplotlib>=2.0.0
    - seaborn>=0.7.1
    - ipython>=5.3.0
    - notebook>=4.4.1
    - pandas-datareader>=0.5.0
    - distributed
    - pyarrow
  commands:
    - pip check
    - pytest -v tests --ignore=tests/integrations
  imports:
    - tsfresh

about:
  home: https://github.com/blue-yonder/tsfresh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Automatic extraction of relevant features from time series
  description: |
    The package provides systematic time-series feature extraction by combining established algorithms 
    from statistics, time-series analysis, signal processing, and nonlinear dynamics with a robust 
    feature selection algorithm. In this context, the term time-series is interpreted in the broadest 
    possible sense, such that any types of sampled data or even event sequences can be characterized.
  doc_url: https://tsfresh.readthedocs.io/
  dev_url: https://github.com/blue-yonder/tsfresh

extra:
  recipe-maintainers:
    - MaxBenChrist
    - nils-braun
    - xhochy
