{% set name = "tsfresh" %}
{% set version = "0.13.0" %}
{% set sha256 = "a6ddce6ddbbb26a709fcfbade0e83ae052ead9b30bb1de2d2307640d81e2c875" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - six
  run:
    - python
    - setuptools
    - requests >=2.9.1
    - numpy >=1.10.4
    - pandas >=0.20.3, <=0.23.4
    - scipy >=1.2.0
    - statsmodels >=0.8.0
    - patsy >=0.4.1
    - scikit-learn >=0.19.0
    - future >=0.16.0
    - six >=1.10.0
    - tqdm >=4.10.0
    - dask>=0.15.2
    - distributed>=1.18.3

test:
  imports:
    - tsfresh

about:
  home: http://github.com/blue-yonder/tsfresh
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Automatic extraction of relevant features from time series'

  doc_url: http://tsfresh.readthedocs.io/
  dev_url: https://github.com/blue-yonder/tsfresh

extra:
  recipe-maintainers:
    - MaxBenChrist
    - nils-braun
    - xhochy
