travis:
  secure:
    BINSTAR_TOKEN: Q6d9DvzqRuNTll6yQiV2lxiX2ddXR8LHWpLrzOZbnif+sqZSe9ULEIQJKGnkr0XsIo3zMSmcMZ5cOn4Jr/Fo8zu9lnfWTfygvoPiBOVwfi70E+/ZtRrSJLnFNUsaAm0v9BN9FUkyjSsnA9upC6T2VJd+c94ftJfZ5l4TrJjGUj71871roNUPwHXxt0AcvbO2LznRhAaqAx4EWd+35b/hgurZAf77oQvlusfNI1HP5SucP8X/o9UMvXqGKzej3CW3sNW331IM6jaSN68/nyxr+lxqu40eddOWsf8mVZpzm+TbXM9DKPbT+0iOwoWxvJBVSkG5CM1WldORikKgfqma09loXMqzDcwobJQecAdBuFSZstF9u78HuFNIvmbjZEEjTdh1MWdVAG84+MX3YcLrzgSvX4D/aXlzI7WX3PR0TCHzFWxnc8mJXqgaudz7H17X5v0evXdoGSpqnb525UH9BmaaWQir5zZFoXUwfOc1f6vl+oFSGvfOiv5+a39OSbz1vSJKcQwlvc6PCnSqbtI3X+ZjlwnkHABS2/UqgVwOOUaWqNmRxpabAZLQ/Yobi+6rBa1vq02xZS7RfyP9ZPAZm2LZIj+Ako4baeCYdtdixH2NA8x0bCYeX+k1Td3KDiAZ0TsJUlCGvh4rtpCAnVOhydJ2fDRah4FGrZOpdQQWCCc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
