travis:
  secure:
    BINSTAR_TOKEN: F21Iy6dMh3kXIDygNxt+8BFySaZ7r3T732gDzUP2YMK6b42zDEjc4817O51xAUHWWKmeBZEVwL/7Wv2uSibSdXRp9IrEYFIW71Hc/xzindzGxmM9LHLjq7kRgWDVkcvMnWTKFIx5qL8gK2AmVrrFHy+T2OJsWOUuRm/bOonLlPqcCuC9IMTCyh+1VPvzpVknSaLR0g9CeuU+upRnfSZy/XVJLHN5m1WjkbjiV9RhRDIxgxG4WK0BRdZhkmL/zS3uf6g/2u+GclgGtwFD2eZbIJAC4KImaKyxuCsFoA1QbUUCIjIoRlfENZ+EWa4j2UpxOkv/C617k1tdTuPko4JSTqU1arkW7mF9zlORAI+kpvCqtEwYxxIYpYIP27TXRmBDJP5ckzsmhhvmlIFtL0Ol31wTAsIVf34ojT02ICD3EalDmEGwDjazNVTUwm0oLL5TcUJAIys2c+VBbr9bjsqbO31oV3MrmKc1am6quwVhVuDC+5i57Xl79fcaLT//zKQQ6wiuSeTh8nAWu/DXNbvTkT1ngHbaA5pgMccGVPy6jGP+NA2xYm9c1ewSO8f1GCnkZ/QO9AAjMJorYVT/YYJhrJpXsO8PNClCwpwTVDuQvGGMIqB5CWeohzBFLtko1KAT1xN7KXVd86OSdD4cXsz+TWvC+SBsHvzLr5AHuqYkeo8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
